### ISSUE TITLE
doesn't respect zIndex property

### ISSUE THREAD

**Issue by mariusnita** [CartoDB/Leaflet.CanvasLayer#2]
Thanks for the work on CanvasLayer, it's great. I have 

``` js
Layer1 = L.CanvasLayer.extend({ ... });
Layer2 = L.CanvasLayer.extend({ ... });
map.addLayer(new Layer1({zIndex: 10}));
map.addLayer(new Layer2({zIndex: 20}));
```

But when turning layers on and off, the zIndex property is not respected. The latest added layer is always on top. I noticed I can fix it by adding the line

``` js
this._staticPane.style.zIndex = this.options.zIndex;
```

to the function onAdd, but I'm not sure if this is the comprehensive fix.

**Comment by javisantana** [comment]
I didn't add support for zIndex but is a good thing to add.

Related to your fix: it works because there is a bug in the layer which includes a staticPane each layer is added instead of reusing the previous one. 

The correct one would be to set the zIndex to the canvas itself (now it wouldn't work)
